#!/bin/sh
set -e
cargo build
cp target/debug/libsolira.dylib bin/
cp plugin_config.json bin/
cd bin
CLICOLOR_FORCE=1 solana-test-validator -r --geyser-plugin-config plugin_config.json --log 2>&1 | grep --color=always --line-buffered "solira"
