#!/bin/sh
set -ex
pkill clickhouse || echo ""
cargo build --release -p geyser-replay -p solira
cp plugin_config.json bin/
if [[ "$OSTYPE" == "darwin"* ]]; then
  cp target/release/libsolira.dylib bin/
  cd bin
  awk '{gsub("{{ext}}", "dylib")}1' plugin_config.json > plugin_config.tmp && mv plugin_config.tmp plugin_config.json
else
  cp target/release/libsolira.so bin/
  cd bin
  awk '{gsub("{{ext}}", "so")}1' plugin_config.json > plugin_config.tmp && mv plugin_config.tmp plugin_config.json
fi
awk "{gsub(\"{{full-path}}\", \"$PWD\")}1" plugin_config.json > plugin_config.tmp && mv plugin_config.tmp plugin_config.json
cat plugin_config.json
cp ../target/release/geyser-replay .
./geyser-replay $1 `pwd`/plugin_config.json
#solana-test-validator --geyser-plugin-config plugin_config.json --log
# solana-validator \
#     --identity ~/validator-keypair.json \
#     --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
#     \ #--ledger ~/solana-ledger \
#     --rpc-port 8899 \
#     --geyser-plugin-config plugin_config.json \
#     --no-voting \
#     --limit-ledger-size
