version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: solana-analytics-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - solana-analytics

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: solana-analytics-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - solana-analytics

volumes:
  clickhouse-data:
  clickhouse-logs:
  redis-data:

networks:
  solana-analytics:
    driver: bridge

